[package]
name = "calrov-website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version="0.5.0-rc.2", features=["tls"]}
tera = "1.16.0"
mongodb = "2.2.2"
serde = "1.0.137"
bson = "2.3.0"